-- ARIES club database (SQLite)
-- Runtime file: database/aries.db (generated by seed / backend)

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS members (
  slug TEXT PRIMARY KEY,
  data TEXT NOT NULL,          -- full Member JSON (frontend shape)
  email TEXT,
  level TEXT DEFAULT 'member', -- oc | coordinator | executive | member | alumni
  password_hash TEXT,          -- null = no login
  group_name TEXT,             -- Brain | Canvas
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS projects (
  slug TEXT PRIMARY KEY,
  data TEXT NOT NULL,
  section TEXT,
  featured INTEGER DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS events (
  slug TEXT PRIMARY KEY,
  data TEXT NOT NULL,
  date TEXT,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS resources (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  data TEXT NOT NULL           -- Resource[] JSON
);

CREATE TABLE IF NOT EXISTS team (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  data TEXT NOT NULL           -- TeamData JSON
);

CREATE TABLE IF NOT EXISTS problems (
  slug TEXT PRIMARY KEY,
  data TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS submissions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  problem_slug TEXT NOT NULL,
  member_slug TEXT,
  member_name TEXT NOT NULL,
  score REAL NOT NULL,
  notes TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (problem_slug) REFERENCES problems(slug) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS invoices (
  id TEXT PRIMARY KEY,
  data TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS sessions (
  token TEXT PRIMARY KEY,
  member_slug TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  expires_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_events_date ON events(date);
CREATE INDEX IF NOT EXISTS idx_submissions_problem ON submissions(problem_slug);
